plugins {
    id 'com.android.application'
}

android {
    namespace 'org.synergy'
    compileSdk 35

    defaultConfig {
        applicationId 'org.synergy'
        minSdk 24
        targetSdk 35
        versionCode 21
        versionName '0.0024'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
